language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - os: linux
      dist: precise
      python: 3.8
      addons:
        apt:
          packages:
            - chrpath
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
script: python3 -m nuitka --standalone --onefile --linux-onefile-icon /usr/share/pixmaps/python3.xpm main.py