name: onepy Builder
on:
  release:
    types:
      - published
jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with Nuitka
      run: |
        python -m nuitka --assume-yes-for-downloads --standalone --onefile --linux-onefile-icon /usr/share/pixmaps/python3.xpm main.py
        mv main.bin onepy_nix.bin
        echo upload_url=${{ needs.create_release_job.outputs.upload_url }}
    - name: Get upload_url
      run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
      id: release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./onepy_nix.bin
          asset_name: onepy_nix.bin
          asset_content_type: application/octet-stream
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with Nuitka
      run: |
        python -m nuitka --assume-yes-for-downloads --standalone  --windows-product-version=1.0.0.0 --windows-company-name=onepy --windows-file-description=onepy --onefile main.py
        mv main.exe onepy_win.exe
    - name: Get upload_url
      run: echo "::set-output name=upload_url::https://uploads.github.com/repos/${{ github.repository }}/releases/$(jq --raw-output '.release.id' ${{ github.event.path }})/assets{?name,label}"
      id: release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./onepy_win.exe
          asset_name: onepy_win.exe
          asset_content_type: application/octet-stream
  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with Nuitka
      run: |
        python -m nuitka --assume-yes-for-downloads --standalone main.py
        ls -lah ./main.dist
        mv ./main.dist/main onepy_osx.bin
